plugins:
  - jekyll-polyglot
  - jekyll-minifier
languages: ["en", "es", "de"]
default_lang: "en"
exclude_from_localization: ["assets", "images", "css", "README.md"]
parallel_localization: true
baseurl: /
a_rootpage: "http://127.0.0.1:4000"
githubrepoeditbase: "https://github.com/gilgongo/jamulushome/edit/polyglot"
exclude: ["README.md", "Gemfile.lock", "Gemfile", "CONTRIBUTING.md"]
jekyll-minifier:
  remove_intertag_spaces: true
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
